# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/Arrackisarookie"

[social.params]
icon = "brand-github"

[[social]]
identifier = "mail"
name = "GitHub"
url = "mailto:arrackisarookie@gmail.com"

[social.params]
icon = "mail"

#[[social]]
#identifier = "twitter"
#name = "Twitter"
#url = "https://twitter.com"

#[social.params]
#icon = "brand-twitter"
